### ISSUE TITLE
changed timeout value not used; default instead

### ISSUE THREAD

**Issue by pete-dawgg** [Mibew/purge-history-plugin#1]
The plugin works but does not use the custom timeout value in config.yml; it seems to use the default value instead.
We would like to use a timeout of 60 days and so i set the value
`timeout: 5184000`
in config.yml.
(No other plugin is configured in config.yml and BulkLogsOperations is the only other plugin installed.)
cron is run every hour with wget and works.
But everything older than the last two days is missing now.
How can we configure the plugin to respect the 60-day value?

**Comment by faf** [comment]
1. Provide the section of your configuration related to plugins as is, including whitespaces.

2. What's in the error log of your web server?

**Comment by pete-dawgg** [comment]
THX for your reply!
The config.yml (with only the plugin-section) is attached as config.txt
Getting the webserver-log can take some time (as the server is run by another dept), but we have a testing environment. What errors shoul i look for there?




[config.txt](https://github.com/Mibew/purge-history-plugin/files/5635993/config.txt)

**Comment by faf** [comment]
"Mibew:PurgeHistory" and "Mibew:purgeHistory" are not equal. ;)

One should use the valid plugin name in the configuration.
